
language: python
python:
 - "3.8"
install:
 - pip install PrettyTable
# command to run tests
script:
 - python -m unittest us01_test
 - python -m unittest us02_test
 - python -m unittest us03_test
 - python -m unittest us04_test
 - python -m unittest us05_test
 - python -m unittest us07_test
 - python -m unittest us08_test
 - python -m unittest us09_test
 - python -m unittest us17_test
 - python -m unittest us18_test
 - python -m unittest us06_test
 - python -m unittest us12_test
 - python -m unittest us10_test
 - python -m unittest us11_test
 - python -m unittest us15_test
 - python -m unittest us16_test
 - python -m unittest us13_test
 - python -m unittest us14_test
 - python -m unittest us23_test
 - python -m unittest us24_test
